//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcom.Invoices.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public CustomerMaster()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public string CustomerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string LegalAddress { get; set; }
        public string SearchKey { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string VATRegistrationNo { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string TradingPartner { get; set; }
        public System.DateTime DateTime { get; set; }
        public int F_identity { get; set; }
        public byte StatusData { get; set; }
        public string Encryptkey { get; set; }
    
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
