//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcom.Invoices.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int F_identity { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string OrderNo { get; set; }
        public string CustomerID { get; set; }
        public string MerchantID { get; set; }
        public int VinID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte StatusData { get; set; }
        public string Encryptkey { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual Reconcile Reconcile { get; set; }
    }
}
