//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcom.Invoices.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceProductions = new HashSet<InvoiceProduction>();
        }
    
        public int InvoiceKey { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string CustomerID { get; set; }
        public string CusName { get; set; }
        public string CusCom { get; set; }
        public string CusAddress { get; set; }
        public string CusPhone { get; set; }
        public string CusTaxCode { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> VatAmount0 { get; set; }
        public Nullable<decimal> GrossValue0 { get; set; }
        public Nullable<decimal> VatAmount5 { get; set; }
        public Nullable<decimal> GrossValue5 { get; set; }
        public Nullable<decimal> VatAmount10 { get; set; }
        public Nullable<decimal> GrossValue10 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountInWords { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string Pattern { get; set; }
        public string Serial1 { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string VDCKey { get; set; }
    
        public virtual ICollection<InvoiceProduction> InvoiceProductions { get; set; }
    }
}
