//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcom.Invoices.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceProduction
    {
        public int InvoiceKey { get; set; }
        public int InvoiceProductID { get; set; }
        public int ReconcileKey { get; set; }
        public int VinID { get; set; }
        public string ProdName { get; set; }
        public string ProdUnit { get; set; }
        public decimal ProdQuantity { get; set; }
        public decimal ProdPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int VATRate { get; set; }
        public decimal VATAmount { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> AmountICLVAT { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
