//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcom.Invoices.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReconcileDBEntities1 : DbContext
    {
        public ReconcileDBEntities1()
            : base("name=ReconcileDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomerMaster> CustomerMasters { get; set; }
        public DbSet<CustomerOrder> CustomerOrders { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<InvoiceProduction> InvoiceProductions { get; set; }
        public DbSet<Reconcile> Reconciles { get; set; }
        public DbSet<VinID_Service> VinID_Service { get; set; }
        public DbSet<VinID_Trading> VinID_Trading { get; set; }
    }
}
