//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcom.Invoices.Web.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Reconcile
    {
        public Reconcile()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }

        public int ReconcileKey { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string OrderNo { get; set; }
        public int VinID { get; set; }
        public decimal ProdPrice { get; set; }
        public int ProdType { get; set; }
        public string ProdName { get; set; }
        public int VATRate { get; set; }
        public decimal VATAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal Quantity { get; set; }
        public decimal AmountBeforeVAT { get; set; }
        public decimal InterestAmount { get; set; }
        public string MerchantID { get; set; }
        public string MerchantName { get; set; }
        public decimal Amount { get; set; }
        public decimal ReturnAmount { get; set; }
        public decimal NotDeliveryAmount { get; set; }
        public decimal ReturnMerchantAmount { get; set; }
        public int Status { get; set; }
        public int TotalRecord { get; set; }

        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual VinID_Service VinID_Service { get; set; }
        public virtual VinID_Trading VinID_Trading { get; set; }
    }
}
